### ISSUE TITLE
Questions in inpainting.py

### ISSUE THREAD

**Issue by wurongyuan** [edongdongchen/EI#1]
In inpainting.py, why is function A the same as function A_dagger?  Shouldn't they be inverting each other?

**Comment by edongdongchen** [comment]
Hello, the reason is that in inpainting, if we regard the input as a long vector, the forward operator A is actually a diagonal matrix diag(b) where b is a binary mask. A's pseudo inverse is then computed as A due to its binary value and Hadamard’s product computation (see A's description on the paper's 8th page). Let me know if it doesn't make sense.

**Comment by wurongyuan** [comment]
In inpainting, according the description: y=b.x (x, y are both matrices) and y=Ax (x, y are both vectors) , where A= diag(b).
if A = A-1, then, A-1y = y, which seems to be true in the inpainting case of Fig. 1

**Comment by wurongyuan** [comment]
In inpainting, according the description: y=b.x (x, y are both matrices) and y=Ax (x, y are both vectors) , where A= diag(b).
if A = A-1, then, A-1y = y, which seems to be true in the inpainting case of Fig. 1
if so, there seems to be no point in the existence of A,  do I understand it correctly?

**Comment by wurongyuan** [comment]
In inpainting, according the description: y=b.x (x, y are both matrices) and y=Ax (x, y are both vectors) , where A= diag(b).
if A = A-1, then, A-1y = y, which seems to be true in the inpainting case of Fig. 1
if so, there seems to be no point in the existence of A-1, do I understand it correctly?

**Comment by edongdongchen** [comment]
The A is usually not invertible as it's ill-posed (e.g. not full rank), for example in inpainting, diag(b) is a sparse and 0-1diagonal matrix. Here we used the pseudo-inverse (or its cheap approximation) to project the measurement into the data space to first get a coarse reconstruction. Note you don't always need to involve the pseudo-inverse, i.e. you can also direct define f=net(y) without involving the pseudo-inverse. It only depends on the construction of f which is fundamentally very flexible.

**Comment by wurongyuan** [comment]
Thank you for answering my question. I get it.
