### ISSUE TITLE
Extending EI to

### ISSUE THREAD

**Issue by fkmajiji** [edongdongchen/EI#2]
When I extended the EI to demosaicing problem, I found that I could not train the network in a completely unsupervised way: I must pre-train the network using synthetic data in supervised way, and then fine-tune some components of the network using the real data with unsupervised EI strategy, which seems to conflict with your research findings.

It should be noted that the sampling operation in the demosaicing problem is periodic, so the number of effective shift transformations G is limited, making m|G|=n. So I would like to ask you if this is the reason why my demosaicing network cannot be trained completely unsupervised? On the basis of translation transformation, will adding rotation and other transformations help this dilemma?

In addition, you stated in your paper that EI strategy does not pick the network, which is a very good point.  Have you studied whether different network structures would cause fluctuations in the final performance? 

Thank you very much for your reading and I am looking forward to your reply.

**Comment by edongdongchen** [comment]
Yes, you should try any other invariances such that the forward operator is not invariant to the group action.  You may check my sent email for a detailed comment.
